export const ErrorCodes = {
    // Authentication (AUTH0xx)
    AUTH_INVALID_CREDENTIALS: 'AUTH001',
    AUTH_USER_EXISTS: 'AUTH002',
    AUTH_TOKEN_EXPIRED: 'AUTH003',
    AUTH_TOKEN_INVALID: 'AUTH004',
    AUTH_REFRESH_TOKEN_INVALID: 'AUTH005',
    AUTH_ACCOUNT_LOCKED: 'AUTH006',
    AUTH_ACCOUNT_INACTIVE: 'AUTH007',
    AUTH_ACCOUNT_SUSPENDED: 'AUTH008',
    AUTH_PASSWORD_WEAK: 'AUTH009',
    AUTH_PASSWORD_MISMATCH: 'AUTH010',
    AUTH_RESET_TOKEN_INVALID: 'AUTH011',
    AUTH_RESET_TOKEN_EXPIRED: 'AUTH012',
    AUTH_UNAUTHORIZED: 'AUTH013',
    AUTH_SESSION_EXPIRED: 'AUTH014',
    AUTH_SESSION_INVALID: 'AUTH015',
    AUTH_MAX_SESSIONS_EXCEEDED: 'AUTH016',
    AUTH_DEVICE_NOT_RECOGNIZED: 'AUTH017',

    // User (USR0xx)
    USER_NOT_FOUND: 'USR001',
    USER_EMAIL_EXISTS: 'USR002',
    USER_UPDATE_FAILED: 'USR003',
    USER_DELETE_FAILED: 'USR004',

    // Validation (VAL0xx)
    VALIDATION_FAILED: 'VAL001',
    INVALID_INPUT: 'VAL002',

    // System (SYS0xx)
    INTERNAL_ERROR: 'SYS001',
    DATABASE_ERROR: 'SYS002',
    RATE_LIMIT_EXCEEDED: 'SYS003',
    FORBIDDEN: 'SYS004',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
